start transaction;
set constraints all deferred;

insert into juntagrico_activityarea(id,
name, 
description, 
core, 
hidden, 
show_coordinator_phonenumber, 
coordinator_id ) select id,
name, 
description, 
core, 
hidden, 
show_coordinator_phonenumber, 
coordinator_id from my_ortoloco_taetigkeitsbereich;

insert into juntagrico_activityarea_members(id, 
activityarea_id, 
member_id) select id, 
taetigkeitsbereich_id, 
loco_id from my_ortoloco_taetigkeitsbereich_locos;

insert into juntagrico_assignment(id, 
core_cache, 
job_id, 
member_id)
select id, 
core_cache, 
job_id, 
loco_id from my_ortoloco_boehnli;

insert into juntagrico_billable(id, 
polymorphic_ctype_id) select id, 
polymorphic_ctype_id from my_ortoloco_billable;

insert into juntagrico_depot(id, 
code, 
name, 
weekday, 
latitude, 
longitude, 
addr_street, 
addr_zipcode, 
addr_location, 
description, 
contact_id) select id, 
code, 
name, 
weekday, 
latitude, 
longitude, 
addr_street, 
addr_zipcode, 
addr_location, 
description, 
contact_id from my_ortoloco_depot;

insert into juntagrico_extrasubscription(billable_ptr_id, 
active, 
canceled, 
activation_date, 
deactivation_date, 
main_subscription_id, 
type_id) select billable_ptr_id,
active, 
canceled, 
activation_date, 
deactivation_date, 
main_abo_id, 
type_id from my_ortoloco_extraabo;

insert into juntagrico_extrasubscriptioncategory(id, 
name, 
description, 
sort_order) select id, 
name, 
description, 
sort_order from my_ortoloco_extraabocategory;

insert into juntagrico_extrasubscriptiontype(id, 
name, 
size, 
description, 
sort_order, 
category_id) select id, 
name, 
size, 
description, 
sort_order, 
category_id from my_ortoloco_extraabotype;

insert into juntagrico_job(id, 
slots, 
time, 
pinned, 
reminder_sent, 
canceled, 
polymorphic_ctype_id)select id, 
slots, 
time, 
pinned, 
reminder_sent, 
canceled, 
polymorphic_ctype_id from my_ortoloco_job;

insert into juntagrico_jobtype(id, 
name, 
displayed_name, 
description, 
duration, 
location, 
activityarea_id) select id, 
name, 
displayed_name, 
description, 
duration, 
location, 
bereich_id from my_ortoloco_jobtype;

insert into juntagrico_mailtemplate(id, 
name, 
template, 
code) select id, 
name, 
template, 
code from my_ortoloco_mailtemplate;

insert into juntagrico_member(id, 
first_name, 
last_name, 
email, 
addr_street, 
addr_zipcode, 
addr_location, 
birthday, 
phone, 
mobile_phone, 
confirmed, 
reachable_by_email, 
block_emails, 
user_id, 
subscription_id) select id, 
first_name, 
last_name, 
email, 
addr_street, 
addr_zipcode, 
addr_location, 
birthday, 
phone, 
mobile_phone, 
confirmed, 
reachable_by_email, 
block_emails, 
user_id, 
abo_id from my_ortoloco_loco;

insert into juntagrico_onetimejob(job_ptr_id, 
name, 
displayed_name, 
description, 
duration, 
location, 
activityarea_id) select job_ptr_id, 
name, 
displayed_name, 
description, 
duration, 
location, 
bereich_id from my_ortoloco_onetimejob;

insert into juntagrico_recuringjob(job_ptr_id, 
type_id) select job_ptr_id, 
typ_id from my_ortoloco_recuringjob;

insert into juntagrico_share(billable_ptr_id, 
paid_date, 
issue_date, 
booking_date, 
cancelled_date, 
termination_date, 
payback_date, 
number, 
notes, 
member_id) select  
billable_ptr_id, 
paid_date, 
issue_date, 
booking_date, 
cancelled_date, 
termination_date, 
payback_date, 
number, 
notes, 
loco_id 
from my_ortoloco_anteilschein;

insert into juntagrico_subscription(billable_ptr_id, 
size, 
future_size, 
active, 
activation_date, 
deactivation_date, 
creation_date, 
start_date, 
depot_id, 
future_depot_id, 
primary_member_id) select billable_ptr_id, 
size, 
future_size, 
active, 
activation_date, 
deactivation_date, 
creation_date, 
start_date, 
depot_id, 
future_depot_id, 
primary_loco_id from my_ortoloco_abo;

insert into juntagrico_subscriptionsize(id, 
name, 
long_name, 
size, 
shares, 
required_assignments, 
price, 
depot_list, 
description) select id, 
name, 
long_name, 
size, 
shares, 
0, 
0, 
depot_list, 
description from my_ortoloco_abosize;

commit;